export default [
  { name: 'English (India)', id: 'en-IN' },
  { name: 'English (United States)', id: 'en-US' },
  { name: 'Italian (Italy)', id: 'it-IT' },
  { name: 'Swedish (Sweden)', id: 'sv-SE' },
  { name: 'French (Canada)', id: 'fr-CA' },
  { name: 'Malay (Malaysia)', id: 'ms-MY' },
  { name: 'German (Germany)', id: 'de-DE' },
  { name: 'English (United Kingdom)', id: 'en-GB' },
  { name: 'Hebrew (Israel)', id: 'he-IL' },
  { name: 'English (Australia)', id: 'en-AU' },
  { name: 'Indonesian (Indonesia)', id: 'id-ID' },
  { name: 'French (France)', id: 'fr-FR' },
  { name: 'Bulgarian (Bulgaria)', id: 'bg-BG' },
  { name: 'Spanish (Spain)', id: 'es-ES' },
  { name: 'Spanish (Mexico)', id: 'es-MX' },
  { name: 'Finnish (Finland)', id: 'fi-FI' },
  { name: 'Portuguese (Brazil)', id: 'pt-BR' },
  { name: 'Dutch (Belgium)', id: 'nl-BE' },
  { name: 'Japanese (Japan)', id: 'ja-JP' },
  { name: 'Romanian (Romania)', id: 'ro-RO' },
  { name: 'Portuguese (Portugal)', id: 'pt-PT' },
  { name: 'Thai (Thailand)', id: 'th-TH' },
  { name: 'Croatian (Croatia)', id: 'hr-HR' },
  { name: 'Slovak (Slovakia)', id: 'sk-SK' },
  { name: 'Hindi (India)', id: 'hi-IN' },
  { name: 'Ukrainian (Ukraine)', id: 'uk-UA' },
  { name: 'Chinese (China)', id: 'zh-CN' },
  { name: 'Vietnamese (Vietnam)', id: 'vi-VN' },
  { name: 'Arabic (Generic)', id: 'ar-001' },
  { name: 'Chinese (Taiwan)', id: 'zh-TW' },
  { name: 'Greek (Greece)', id: 'el-GR' },
  { name: 'Russian (Russia)', id: 'ru-RU' },
  { name: 'English (Ireland)', id: 'en-IE' },
  { name: 'Catalan (Spain)', id: 'ca-ES' },
  { name: 'Norwegian Bokmål (Norway)', id: 'nb-NO' },
  { name: 'Danish (Denmark)', id: 'da-DK' },
  { name: 'Chinese (Hong Kong SAR)', id: 'zh-HK' },
  { name: 'English (South Africa)', id: 'en-ZA' },
  { name: 'Hungarian (Hungary)', id: 'hu-HU' },
  { name: 'Dutch (Netherlands)', id: 'nl-NL' },
  { name: 'Turkish (Turkey)', id: 'tr-TR' },
  { name: 'Korean (South Korea)', id: 'ko-KR' },
  { name: 'Polish (Poland)', id: 'pl-PL' },
  { name: 'Czech (Czech Republic)', id: 'cs-CZ' },
  { name: 'Spanish (United States)', id: 'es-US' },
];

export type TLang = {
  name: string;
  id: string;
};
